FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.22 as builder

WORKDIR /go/src/github.com/stolostron/cluster-curator-controller
COPY . .

RUN make compile-curator

#RUN go build -o build/_output/curator ./pkg/jobs/curator.go
#RUN go build -o build/_output/cluster-curator-controller ./pkg/controller/controller.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV USER_UID=1001

# Add the binaries
COPY --from=builder /go/src/github.com/stolostron/cluster-curator-controller/build/_output/curator .
COPY --from=builder /go/src/github.com/stolostron/cluster-curator-controller/build/_output/manager .

USER ${USER_UID}
