#FROM registry.ci.openshift.org/open-cluster-management/builder:go1.15-linux-amd64 AS builder
FROM registry.ci.openshift.org/open-cluster-management/builder:go1.16-linux as builder

WORKDIR /go/src/github.com/open-cluster-management/cluster-curator-controller
COPY . .

RUN make compile-curator

#RUN go build -o build/_output/curator ./pkg/jobs/curator.go
#RUN go build -o build/_output/cluster-curator-controller ./pkg/controller/controller.go

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV USER_UID=1001

# Add the binaries
COPY --from=builder /go/src/github.com/open-cluster-management/cluster-curator-controller/build/_output/curator .
COPY --from=builder /go/src/github.com/open-cluster-management/cluster-curator-controller/build/_output/manager .

USER ${USER_UID}