## This example has all possible containers(tasks) you can run in the Job
## Add or Remove (comment out) what you do not want to use, and paste this into the cluster ClusterCurator under 
##   spec:
##     install:
##         overrideJob:
####
apiVersion: batch/v1
kind: Job
metadata:
  GenerateName: curator-job-
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: cluster-installer
      initContainers:
      - name: applycloudprovider-aws
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','applycloudprovider-aws']
      - name: applycloudprovider-gcp
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','applycloudprovider-gcp']
      - name: applycloudprovider-azure
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','applycloudprovider-azure']
      - name: applycloudprovider-vmware
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','applycloudprovider-vmware']
      - name: applycloudprovider-ansible
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','applycloudprovider-ansible']
      #########################################
      ## Used as part of standard curation   ##
      #########################################
      - name: prehook-ansiblejob
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','prehook-ansiblejob']
        env:
          - name:  "JOB_TYPE"
            value: "prehook"
      - name: activate-and-monitor
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','activate-and-monitor']
      - name: monitor                                       # Not part of standard curation
        image: quay.io/jpacker/clustercurator-job:latest    #
        command: ['./curator','monitor']                    #
      - name: monitor-import
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','monitor-import']
      - name: posthook-ansiblejob
        image: quay.io/jpacker/clustercurator-job:latest
        command: ['./curator','posthook-ansiblejob']
        env:
          - name:  "JOB_TYPE"
            value: "posthook"
      containers:
      - name: complete
        image: quay.io/jpacker/clustercurator-job:latest
        imagePullPolicy: Always
        #command: ['echo','Done! create'] # Use this to preserve the conditions
        command: ['./curator','done']
      restartPolicy: Never
