---
apiVersion: v1
kind: Template
metadata:
  name: cluster-curator-controller
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: cluster-curator-controller
    name: cluster-curator-controller
    namespace: open-cluster-management
  spec:
    replicas: 2
    selector:
      matchLabels:
        name: cluster-curator-controller
    template:
      metadata:
        labels:
          name: cluster-curator-controller
      spec:
        serviceAccountName: cluster-curator
        containers:
        - image: ${REPO_URL}/cluster-curator-controller@${IMAGE_SHA}
          name: cluster-curator-controller
          imagePullPolicy: Always
          command: ["./manager","-enable-leader-election"]
          imagePullPolicy: Always
          env:
          - name: IMAGE_TAG
            value: "${IMAGE_SHA}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          resources:
            limits:
              cpu: "10m"
              memory: "45Mi"
            requests:
              cpu: "3m"                     # Runs < 2m most of the time
              memory: "25Mi"                # Runs between 25-28Mi
parameters:
- description: SHA tag to use with the containers
  name: IMAGE_SHA
  required: true
- description: Where to pull the image
  name: REPO_URL
  required: true