// +build !ignore_autogenerated

// Copyright (c) 2020 Red Hat, Inc.
// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCurator) DeepCopyInto(out *ClusterCurator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCurator.
func (in *ClusterCurator) DeepCopy() *ClusterCurator {
	if in == nil {
		return nil
	}
	out := new(ClusterCurator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCurator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorList) DeepCopyInto(out *ClusterCuratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCurator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorList.
func (in *ClusterCuratorList) DeepCopy() *ClusterCuratorList {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCuratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorSpec) DeepCopyInto(out *ClusterCuratorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorSpec.
func (in *ClusterCuratorSpec) DeepCopy() *ClusterCuratorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorStatus) DeepCopyInto(out *ClusterCuratorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorStatus.
func (in *ClusterCuratorStatus) DeepCopy() *ClusterCuratorStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorStatus)
	in.DeepCopyInto(out)
	return out
}
