apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-curator-controller?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "backplane-2.8"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/component: cluster-curator-controller-mce-28
    pipelines.appstudio.openshift.io/type: build
  name: cluster-curator-controller-mce-28-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/ppc64le
    - linux/s390x
    - linux/arm64
  - name: dockerfile
    value: Dockerfile.rhtap
  - name: path-context
    value: .
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "."}]'
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common_mce_2.8.yaml
  workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-cluster-curator-controller-mce-28
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
